apiVersion: v1
kind: Service
metadata:
  name: planning-mysql-service
  labels:
    app: planning-mysql-service
    service: planning-mysql-service
spec:
  type: LoadBalancer
  ports:
   - name: http
     protocol : TCP
     port: 3306
     targetPort: 3306
  selector:
    app: mysql
